[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.0.0"
futures = { version = "0.3.0", features = ["thread-pool"]}
tokio = { version = "1.21.0", features = ["full"] }
tokio-util = { version = "0.7.0", features = ["full"] }